# ===================================
#  Relation Behavior Config
# ===================================

users:
    label: Users
    view:
        showSearch: true
        list:  ~/plugins/xnok/membership/models/job/users_columns.yaml
        toolbarButtons: add|remove
    manage:
        schowSeach: true
        form: ~/plugins/xnok/membership/models/profile/user_fields.yaml
        recordsPerPage: 20