# ===================================
#  List Behavior Config
# ===================================

# List Title
title: Manage Members
# Model List Column configuration
list: $/xnok/membership/models/profile/users_columns.yaml
# Model Class name
modelClass: Backend\Models\User
# Options
recordUrl: xnok/membership/members/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
# showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt